// Arabic to English transliteration map
const arabicToEnglishMap: Record<string, string> = {
  // Common Arabic words to English translations
  'إدارة': 'management',
  'المستخدمين': 'users',
  'المستخدم': 'user',
  'إنشاء': 'create',
  'إضافة': 'add',
  'تعديل': 'edit',
  'حذف': 'delete',
  'عرض': 'view',
  'قائمة': 'list',
  'الإعدادات': 'settings',
  'إعدادات': 'settings',
  'الحساب': 'account',
  'حساب': 'account',
  'تسجيل': 'register',
  'الدخول': 'login',
  'الخروج': 'logout',
  'كلمة': 'word',
  'المرور': 'password',
  'السر': 'password',
  'البريد': 'email',
  'الإلكتروني': 'electronic',
  'الهاتف': 'phone',
  'رقم': 'number',
  'اسم': 'name',
  'الاسم': 'name',
  'العنوان': 'title',
  'عنوان': 'address',
  'الوصف': 'description',
  'وصف': 'description',
  'المحتوى': 'content',
  'محتوى': 'content',
  'الصفحة': 'page',
  'صفحة': 'page',
  'الصفحات': 'pages',
  'المقال': 'article',
  'مقال': 'article',
  'المقالات': 'articles',
  'القسم': 'section',
  'قسم': 'section',
  'الأقسام': 'sections',
  'الفئة': 'category',
  'فئة': 'category',
  'الفئات': 'categories',
  'التصنيف': 'classification',
  'تصنيف': 'category',
  'البحث': 'search',
  'بحث': 'search',
  'النتائج': 'results',
  'نتائج': 'results',
  'التقرير': 'report',
  'تقرير': 'report',
  'التقارير': 'reports',
  'الإشعارات': 'notifications',
  'إشعار': 'notification',
  'الرسائل': 'messages',
  'رسالة': 'message',
  'الملفات': 'files',
  'ملف': 'file',
  'الصور': 'images',
  'صورة': 'image',
  'الفيديو': 'video',
  'فيديو': 'video',
  'التحميل': 'download',
  'تحميل': 'upload',
  'الرفع': 'upload',
  'رفع': 'upload',
  'المساعدة': 'help',
  'مساعدة': 'help',
  'الدعم': 'support',
  'دعم': 'support',
  'الفني': 'technical',
  'التذاكر': 'tickets',
  'تذكرة': 'ticket',
  'الطلب': 'request',
  'طلب': 'request',
  'الطلبات': 'requests',
  'العميل': 'client',
  'عميل': 'client',
  'العملاء': 'clients',
  'الشركة': 'company',
  'شركة': 'company',
  'المؤسسة': 'organization',
  'مؤسسة': 'organization',
  'الموظف': 'employee',
  'موظف': 'employee',
  'الموظفين': 'employees',
  'الفريق': 'team',
  'فريق': 'team',
  'المشروع': 'project',
  'مشروع': 'project',
  'المشاريع': 'projects',
  'المهمة': 'task',
  'مهمة': 'task',
  'المهام': 'tasks',
  'الجدول': 'schedule',
  'جدول': 'table',
  'التاريخ': 'date',
  'تاريخ': 'date',
  'الوقت': 'time',
  'وقت': 'time',
  'اليوم': 'today',
  'يوم': 'day',
  'أمس': 'yesterday',
  'غداً': 'tomorrow',
  'الأسبوع': 'week',
  'أسبوع': 'week',
  'الشهر': 'month',
  'شهر': 'month',
  'السنة': 'year',
  'سنة': 'year',
  'الموعد': 'appointment',
  'موعد': 'appointment',
  'المواعيد': 'appointments',
  'الاجتماع': 'meeting',
  'اجتماع': 'meeting',
  'الاجتماعات': 'meetings',
  'النظام': 'system',
  'نظام': 'system',
  'البرنامج': 'program',
  'برنامج': 'software',
  'التطبيق': 'application',
  'تطبيق': 'app',
  'الواجهة': 'interface',
  'واجهة': 'interface',
  'لوحة': 'panel',
  'اللوحة': 'dashboard',
  'التحكم': 'control',
  'القيادة': 'dashboard',
  'الرئيسية': 'home',
  'رئيسية': 'main',
  'الأولى': 'first',
  'أولى': 'first',
  'البداية': 'start',
  'بداية': 'start',
  'النهاية': 'end',
  'نهاية': 'end',
  'المقدمة': 'introduction',
  'مقدمة': 'intro',
  'دليل': 'guide',
  'الدليل': 'guide',
  'استخدام': 'usage',
  'الاستخدام': 'usage',
  'كيفية': 'how-to',
  'طريقة': 'method',
  'الطريقة': 'method',
  'خطوات': 'steps',
  'الخطوات': 'steps',
  'خطوة': 'step',
  'شرح': 'explanation',
  'الشرح': 'explanation',
  'التعليمات': 'instructions',
  'تعليمات': 'instructions',
  'الدرس': 'lesson',
  'درس': 'lesson',
  'الدروس': 'lessons',
  'التعلم': 'learning',
  'تعلم': 'learn',
  'التدريب': 'training',
  'تدريب': 'training',
  'الممارسة': 'practice',
  'ممارسة': 'practice',
  'التجربة': 'experience',
  'تجربة': 'trial',
  'المثال': 'example',
  'مثال': 'example',
  'الأمثلة': 'examples',
  'النموذج': 'form',
  'نموذج': 'template',
  'القالب': 'template',
  'قالب': 'template',
  'القوالب': 'templates',
  'التصميم': 'design',
  'تصميم': 'design',
  'اللون': 'color',
  'الألوان': 'colors',
  'الخط': 'font',
  'الخطوط': 'fonts',
  'الحجم': 'size',
  'حجم': 'size',
  'العرض': 'width',
  'الطول': 'height',
  'الارتفاع': 'height',
  'الموقع': 'website',
  'موقع': 'site',
  'الرابط': 'link',
  'رابط': 'link',
  'الروابط': 'links',
  'زر': 'button',
  'الزر': 'button',
  'الأزرار': 'buttons',
  'الحقل': 'field',
  'حقل': 'field',
  'الحقول': 'fields',
  'المدخلات': 'inputs',
  'مدخل': 'input',
  'المخرجات': 'outputs',
  'مخرج': 'output',
  'الجديد': 'new',
  'جديد': 'new',
  'القديم': 'old',
  'قديم': 'old',
  'الأخير': 'latest',
  'أخير': 'last',
  'الأول': 'first',
  'أول': 'first',
  'الكل': 'all',
  'كل': 'all',
  'بعض': 'some',
  'البعض': 'some',
  'أي': 'any',
  'لا': 'no',
  'نعم': 'yes',
  'صحيح': 'correct',
  'خطأ': 'error',
  'الخطأ': 'error',
  'الأخطاء': 'errors',
  'المشكلة': 'problem',
  'مشكلة': 'issue',
  'المشاكل': 'problems',
  'الحل': 'solution',
  'حل': 'solve',
  'الحلول': 'solutions',
  'التحديث': 'update',
  'تحديث': 'update',
  'التحديثات': 'updates',
  'التغيير': 'change',
  'تغيير': 'change',
  'التغييرات': 'changes',
  'الإصدار': 'version',
  'إصدار': 'release',
  'الإصدارات': 'versions',
  'الميزة': 'feature',
  'ميزة': 'feature',
  'الميزات': 'features',
  'الخاصية': 'property',
  'خاصية': 'property',
  'الخصائص': 'properties',
  'الأمان': 'security',
  'أمان': 'security',
  'الحماية': 'protection',
  'حماية': 'protection',
  'الصلاحيات': 'permissions',
  'صلاحية': 'permission',
  'الصلاحية': 'permission',
  'الدور': 'role',
  'دور': 'role',
  'الأدوار': 'roles',
  'المدير': 'admin',
  'مدير': 'manager',
  'المشرف': 'supervisor',
  'مشرف': 'moderator',
  'المحرر': 'editor',
  'محرر': 'editor',
  'الكاتب': 'writer',
  'كاتب': 'author',
  'القارئ': 'reader',
  'قارئ': 'reader',
  'الزائر': 'visitor',
  'زائر': 'visitor',
  'الضيف': 'guest',
  'ضيف': 'guest',
  'التفعيل': 'activation',
  'تفعيل': 'activate',
  'الإلغاء': 'cancel',
  'إلغاء': 'cancel',
  'التأكيد': 'confirmation',
  'تأكيد': 'confirm',
  'الموافقة': 'approval',
  'موافقة': 'approve',
  'الرفض': 'rejection',
  'رفض': 'reject',
  'القبول': 'accept',
  'قبول': 'accept',
  'الانتظار': 'pending',
  'انتظار': 'wait',
  'المعلق': 'pending',
  'معلق': 'suspended',
  'النشط': 'active',
  'نشط': 'active',
  'الخامل': 'inactive',
  'خامل': 'idle',
  'المؤرشف': 'archived',
  'مؤرشف': 'archived',
  'المحذوف': 'deleted',
  'محذوف': 'deleted',
  'المسودة': 'draft',
  'مسودة': 'draft',
  'المنشور': 'published',
  'منشور': 'post',
  'العام': 'public',
  'عام': 'general',
  'الخاص': 'private',
  'خاص': 'special',
  'المخفي': 'hidden',
  'مخفي': 'hidden',
  'الظاهر': 'visible',
  'ظاهر': 'shown',
  'المفضلة': 'favorites',
  'مفضل': 'favorite',
  'المميز': 'featured',
  'مميز': 'special',
  'الأفضل': 'best',
  'أفضل': 'better',
  'الأسوأ': 'worst',
  'أسوأ': 'worse',
  'الأعلى': 'highest',
  'أعلى': 'higher',
  'الأدنى': 'lowest',
  'أدنى': 'lower',
  'الأكبر': 'largest',
  'أكبر': 'bigger',
  'الأصغر': 'smallest',
  'أصغر': 'smaller',
  'والتحديثات': 'and-updates',
  'و': 'and',
  'أو': 'or',
  'من': 'from',
  'إلى': 'to',
  'في': 'in',
  'على': 'on',
  'مع': 'with',
  'بدون': 'without',
  'قبل': 'before',
  'بعد': 'after',
  'خلال': 'during',
  'حول': 'about',
  'عن': 'about',
  'ذلك': 'that',
  'هذا': 'this',
  'هذه': 'these',
  'تلك': 'those',
  'تسجيل الدخول': 'login',
  'تسجيل الخروج': 'logout',
  'إنشاء حساب': 'create-account',
  'نسيت كلمة المرور': 'forgot-password',
  'إعادة تعيين': 'reset',
  'كلمة المرور': 'password',
  'البريد الإلكتروني': 'email',
  'رقم الهاتف': 'phone-number',
  'الاسم الكامل': 'full-name',
  'اسم المستخدم': 'username',
  'الصورة الشخصية': 'profile-picture',
  'الملف الشخصي': 'profile',
  'لوحة التحكم': 'dashboard',
  'إدارة المحتوى': 'content-management',
  'إدارة الملفات': 'file-management',
  'إدارة التذاكر': 'ticket-management',
  'إدارة الاجتماعات': 'meeting-management',
  'دليل الاستخدام': 'user-guide',
  'مركز المساعدة': 'help-center',
  'الأسئلة الشائعة': 'faq',
  'اتصل بنا': 'contact-us',
  'سياسة الخصوصية': 'privacy-policy',
  'شروط الاستخدام': 'terms-of-use',
  'ويبيان': 'webyan',
};

// Arabic letter to Latin transliteration
const arabicLetterMap: Record<string, string> = {
  'ا': 'a', 'أ': 'a', 'إ': 'e', 'آ': 'a',
  'ب': 'b', 'ت': 't', 'ث': 'th',
  'ج': 'j', 'ح': 'h', 'خ': 'kh',
  'د': 'd', 'ذ': 'th', 'ر': 'r',
  'ز': 'z', 'س': 's', 'ش': 'sh',
  'ص': 's', 'ض': 'd', 'ط': 't',
  'ظ': 'z', 'ع': 'a', 'غ': 'gh',
  'ف': 'f', 'ق': 'q', 'ك': 'k',
  'ل': 'l', 'م': 'm', 'ن': 'n',
  'ه': 'h', 'ة': 'h', 'و': 'w',
  'ي': 'y', 'ى': 'a', 'ء': '',
  'ئ': 'e', 'ؤ': 'o', 'ـ': '',
};

/**
 * Transliterate Arabic text to English slug
 */
export function transliterateArabicToEnglish(text: string): string {
  let result = text.trim();
  
  // First, try to match common Arabic phrases/words
  const sortedKeys = Object.keys(arabicToEnglishMap).sort((a, b) => b.length - a.length);
  for (const arabicWord of sortedKeys) {
    const englishWord = arabicToEnglishMap[arabicWord];
    result = result.replace(new RegExp(arabicWord, 'g'), ` ${englishWord} `);
  }
  
  // Then transliterate remaining Arabic letters
  let transliterated = '';
  for (const char of result) {
    if (arabicLetterMap[char] !== undefined) {
      transliterated += arabicLetterMap[char];
    } else if (/[\u0600-\u06FF]/.test(char)) {
      // Skip unknown Arabic characters
      transliterated += '';
    } else {
      transliterated += char;
    }
  }
  
  return transliterated;
}

/**
 * Generate a clean, professional slug from any text (Arabic or English)
 */
export function generateSlug(text: string): string {
  if (!text || !text.trim()) return '';
  
  // Check if text contains Arabic
  const hasArabic = /[\u0600-\u06FF]/.test(text);
  
  let slug = text;
  
  if (hasArabic) {
    // Transliterate Arabic to English
    slug = transliterateArabicToEnglish(text);
  }
  
  return slug
    .toLowerCase()
    .trim()
    // Replace multiple spaces with single space
    .replace(/\s+/g, ' ')
    // Replace spaces with hyphens
    .replace(/\s/g, '-')
    // Remove special characters except hyphens
    .replace(/[^\w-]/g, '')
    // Replace multiple hyphens with single hyphen
    .replace(/-+/g, '-')
    // Remove leading/trailing hyphens
    .replace(/^-+|-+$/g, '');
}

/**
 * Ensure slug is unique by checking against existing slugs
 * Returns the original slug or a suffixed version (-2, -3, etc.)
 */
export async function ensureUniqueSlug(
  slug: string,
  existingSlugs: string[],
  currentId?: string
): Promise<string> {
  const baseSlug = slug;
  let counter = 1;
  let uniqueSlug = slug;
  
  // Create a set for faster lookup, excluding current article's slug
  const slugSet = new Set(existingSlugs);
  
  while (slugSet.has(uniqueSlug)) {
    counter++;
    uniqueSlug = `${baseSlug}-${counter}`;
  }
  
  return uniqueSlug;
}
